version: '3'
services:

  # PHP Service
  resapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: resapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: researchapp
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - resapp-network

  # Nginx Service
  resweb:
    image: nginx:alpine
    container_name: resweb
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - resapp-network

  # MySQL Service
  resdb:
    image: mysql:5.7.22
    container_name: resdb
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: research
      MYSQL_ROOT_PASSWORD: N1mx@9653
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - resdbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - resapp-network

# Docker Networks
networks:
  resapp-network:
    driver: bridge

# Volumes
volumes:
  resdbdata:
    driver: local
