version: '3'
services:

  # PHP Service
  researchapp:
    build:
      context: .
    image: digitalocean.com/php
    container_name: researchapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: researchapp
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/www.conf:/usr/local/etc/php/conf.d/www.conf
    networks:
      - researchapp-network

  # Nginx Service
  researchwebserver:
    image: nginx:alpine
    container_name: researchwebserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - researchapp-network

  # MySQL Service
  researchdb:
    image: mysql:5.7.22
    container_name: researchdb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nimr_research
      MYSQL_ROOT_PASSWORD: N1mx9653
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - researchdbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - researchapp-network

# Docker Networks
networks:
  researchapp-network:
    driver: bridge

# Volumes
volumes:
  researchdbdata:
    driver: local
